CREATE TABLE public.settings (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	ticketnumber int4 NULL,
	settings jsonb NULL,
	CONSTRAINT settings_pkey PRIMARY KEY (id)
);

CREATE TABLE public.tickets (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	ticket_number int8 NOT NULL,
	total float4 NOT NULL,
	pay_method text NOT NULL,
	lines jsonb NOT NULL,
	discount float4 NOT NULL,
	subtotal float4 NOT NULL,
	CONSTRAINT tickets_pkey PRIMARY KEY (id),
	CONSTRAINT tickets_ticket_number_key UNIQUE (ticket_number)
);