name: Backup

on:
  push:
    branches: [ main, feature/supabase ]
  ## Run daily at midnight UTC
  schedule:
    - cron:  '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: postgres:15.6-alpine
      env:
        USER: ${{ secrets.BACKUP_USER }}
        PASSWORD: ${{ secrets.BACKUP_PASSWORD }}
        DB: ${{ secrets.BACKUP_DB }}
        HOST: ${{ secrets.BACKUP_HOST }}
      volumes:
        - ./:/home/backup
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: List directories
      run: |
        echo "ls -l"
        ls -l
        echo "pwd"
        pwd

    - name: Run backup script
      run: |
        echo "Starting backup for host: $HOST DB: $DB"
        echo $PASSWORD | pg_dump -h $HOST -U $USER -W -F t $DB >> /home/backup/backup_$(date +%Y-%m-%dT%H-%M-%S).tar
        
        echo "Backup completed"
        ls -la /home/backup
        exit 0

    - name: Upload backup as artifact
      uses: actions/upload-artifact@v2
      with:
        name: backup
        path: ./