name: Backup

on:
  push:
    branches: [ main, feature/supabase ]
  ## Run daily at midnight UTC
  schedule:
    - cron:  '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: postgres:15.6-alpine
      env:
        USER: ${{ secrets.BACKUP_USER }}
        PASSWORD: ${{ secrets.BACKUP_PASSWORD }}
        DB: ${{ secrets.BACKUP_DB }}
        HOST: ${{ secrets.BACKUP_HOST }}
      volumes:
        - ./backup:/backup
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run backup script
      run: /backup.sh

    - name: Upload backup as artifact
      uses: actions/upload-artifact@v2
      with:
        name: backup
        path: ./backups/