name: Backup

on:
  push:
    branches: [ main, feature/supabase ]
  ## Run daily at midnight UTC
  schedule:
    - cron:  '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run Docker Compose
      run: |
        docker-compose up
        # Aquí puedes ejecutar comandos adicionales si es necesario
    
    - name: Upload backup as artifact
      uses: actions/upload-artifact@v2
      with:
        name: backup
        path: ./backups/