name: Backup

on:
  push:
    branches: [ main, feature/supabase ]
  ## Run daily at midnight UTC
  schedule:
    - cron:  '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run Docker Compose
      env:
        HOST: ${{ secrets.BACKUP_HOST }}
        USER: ${{ secrets.BACKUP_USER }}
        PASSWORD: ${{ secrets.BACKUP_PASSWORD }}
        DB: ${{ secrets.BACKUP_DB }}
      run: |
        apt update
        apt-get install postgresql-client
        
        echo "Starting backup for host: $HOST DB: $DB"
        echo $PASSWORD | pg_dump -h $HOST -U $USER -W -F t $DB >> ./backup/backup_$(date +%Y-%m-%dT%H-%M-%S).tar
        echo "Backup completed"
        exit 0
    - name: Upload backup as artifact
      uses: actions/upload-artifact@v2
      with:
        name: backup
        path: ./backups/